apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: 192.168.13.53
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==